language: python
python:
  - "3.5"

sudo: false

git:
  # Rely on our custom script
  submodules: false

script:
  - python ./scripts/parallel_submodule_update.py
  - git submodule status
  - python ./scripts/check_submodules.py
